version: "3.3"
services:
  app1:
    build: ./app1
    deploy: 
      replicas: 3  
    ports:
    - "5000:5000"
  nginx:
    build: ./nginx
    deploy:
      replicas: 3  
    ports:
    - "9090:80"
