name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cd ./app1 && docker build . --file Dockerfile --tag app1:latest --tag app1:${GITHUB_SHA::6}
